# Generated by Django 2.2.15 on 2020-10-18 02:00

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Имя:')),
                ('surname', models.CharField(blank=True, max_length=32, verbose_name='Фамилия:')),
                ('middle_name', models.CharField(blank=True, max_length=32, verbose_name='Отчество:')),
                ('phone1', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Телефон доп.')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='Город:')),
                ('company', models.CharField(blank=True, max_length=64, verbose_name='Компания:')),
                ('position', models.CharField(blank=True, max_length=32, verbose_name='Должность:')),
                ('comment', models.TextField(blank=True, max_length=16, verbose_name='Комментарий:')),
                ('card', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Номер Карты:')),
                ('watsapp', models.CharField(blank=True, max_length=32, verbose_name='WatsApp:')),
                ('viber', models.CharField(blank=True, max_length=32, verbose_name='Viber:')),
                ('vk', models.CharField(blank=True, max_length=32, verbose_name='ВК:')),
                ('facebook', models.CharField(blank=True, max_length=32, verbose_name='FaceBook:')),
                ('twitter', models.CharField(blank=True, max_length=32, verbose_name='Twitter:')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram:')),
                ('instagram', models.CharField(blank=True, max_length=64, verbose_name='Instagram:')),
            ],
            options={
                'verbose_name': 'Доп. Информация пользователя',
                'verbose_name_plural': 'Доп. Информация пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(max_length=255, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('userpic', models.ImageField(blank=True, null=True, upload_to=account.models.User.profile_pic, verbose_name='Картинка профиля')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Дата последнего входа')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False)),
                ('details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserDetail', verbose_name='Детали')),
                ('usergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserGroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
