# Generated by Django 2.2.15 on 2020-10-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Имя:')),
                ('surname', models.CharField(blank=True, max_length=32, verbose_name='Фамилия:')),
                ('middle_name', models.CharField(blank=True, max_length=32, verbose_name='Отчество:')),
                ('phone1', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Телефон доп.')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='Город:')),
                ('company', models.CharField(blank=True, max_length=64, verbose_name='Компания:')),
                ('position', models.CharField(blank=True, max_length=32, verbose_name='Должность:')),
                ('comment', models.TextField(blank=True, max_length=16, verbose_name='Комментарий:')),
                ('card', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Номер Карты:')),
                ('watsapp', models.CharField(blank=True, max_length=32, verbose_name='WatsApp:')),
                ('viber', models.CharField(blank=True, max_length=32, verbose_name='Viber:')),
                ('vk', models.CharField(blank=True, max_length=32, verbose_name='ВК:')),
                ('facebook', models.CharField(blank=True, max_length=32, verbose_name='FaceBook:')),
                ('twitter', models.CharField(blank=True, max_length=32, verbose_name='Twitter:')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram:')),
                ('instagram', models.CharField(blank=True, max_length=64, verbose_name='Instagram:')),
            ],
            options={
                'verbose_name': 'Доп. Информация пользователя',
                'verbose_name_plural': 'Доп. Информация пользователя',
            },
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserDetail', verbose_name='Детали'),
        ),
    ]
