# Generated by Django 2.2.15 on 2020-10-11 17:44

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Attribute_measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=60, unique=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Attribute_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Наименование атрибута')),
            ],
            options={
                'verbose_name': 'Наименование атрибута',
                'verbose_name_plural': 'Наименование атрибутов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание категории')),
                ('svg', models.CharField(max_length=30, verbose_name='Название SVG, для меню')),
                ('img', models.ImageField(blank=True, upload_to=catalog.models.Category.category_pic, verbose_name='Изображение для категории')),
                ('attr_list', models.ManyToManyField(blank=True, to='catalog.Attribute', verbose_name='Атрибуты для категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название компании')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.FileField(blank=True, upload_to=catalog.models.Manufacturer.manufact_pic, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Логотип')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=120, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=120, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('products', models.TextField(verbose_name='Товары')),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('В обработке', 'В обработке'), ('Готов', 'Готов')], default='Оформлен', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Итоговая стоимость')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('articul', models.IntegerField(verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('img', models.ImageField(upload_to=catalog.models.Product.get_file_path, verbose_name='Главная картинка')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Цена за 1')),
                ('s_description', models.TextField(max_length=600, verbose_name='Краткое описание')),
                ('description', models.TextField(max_length=2000, verbose_name='Полное описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.ProductImages.get_file_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображения товаров',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Attribute_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Пул атрибутов',
                'verbose_name_plural': 'Пул атрибутов',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attribute_measure', verbose_name='Ед. Измерения'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attribute_title', verbose_name='Атрибут'),
        ),
    ]
