# Generated by Django 2.2.15 on 2020-10-21 02:29

import catalog.models
import catalog.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtrributeChoises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choise', models.CharField(max_length=120, unique=True, verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Вариант Selectable',
                'verbose_name_plural': 'Варианты Selectable',
                'db_table': 'attr_choises',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '(4) Атрибут',
                'verbose_name_plural': '(4) Атрибуты',
                'db_table': 'attr',
            },
        ),
        migrations.CreateModel(
            name='Attribute_measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=60, unique=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'db_table': 'attr_measure',
            },
        ),
        migrations.CreateModel(
            name='Attribute_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Наименование атрибута')),
            ],
            options={
                'verbose_name': 'Наименование атрибута',
                'verbose_name_plural': 'Наименование атрибутов',
                'db_table': 'attr_title',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, unique=True, verbose_name='Наименование:')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание категории')),
                ('svg', models.TextField(blank=True, max_length=30, verbose_name='SVG для меню')),
                ('img', models.ImageField(blank=True, upload_to=catalog.models.Category.get_file_path, verbose_name='Изображение')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('attr_list', models.ManyToManyField(blank=True, to='catalog.Attribute', verbose_name='Атрибуты для категории')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category', verbose_name='Категория родитель:')),
            ],
            options={
                'verbose_name': '(2) Категория',
                'verbose_name_plural': '(2) Категории',
                'db_table': 'c_category',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название компании')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.FileField(blank=True, storage=catalog.storage.OverwriteStorage(), upload_to=catalog.models.Manufacturer.manufact_pic, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Логотип')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=120, verbose_name='Ссылка на сайт')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
            ],
            options={
                'verbose_name': '(3) Производитель',
                'verbose_name_plural': '(3) Производители',
                'db_table': 'c_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=120, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=120, verbose_name='E-mail')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('products', models.TextField(verbose_name='Товары')),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('В обработке', 'В обработке'), ('Готов', 'Готов'), ('Отменён', 'Отменён')], default='Оформлен', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Итоговая стоимость')),
            ],
            options={
                'verbose_name': '(6) Заказ',
                'verbose_name_plural': '(6) Заказы',
                'db_table': 'c_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('articul', models.IntegerField(verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('img', models.ImageField(max_length=160, upload_to=catalog.models.Product.get_file_path, verbose_name='Главная картинка')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Цена за 1')),
                ('s_description', models.TextField(max_length=600, verbose_name='Краткое описание')),
                ('description', models.TextField(max_length=2000, verbose_name='Полное описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': '(1) Товар',
                'verbose_name_plural': '(1) Товары',
                'db_table': 'c_product',
            },
        ),
        migrations.CreateModel(
            name='SelectableAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('choises', models.ManyToManyField(to='catalog.AtrributeChoises', verbose_name='Варианты')),
            ],
            options={
                'verbose_name': '(5) Выбираемый атрибут',
                'verbose_name_plural': '(5) Выбираемые атрибуты',
                'db_table': 'attr_selectable',
            },
        ),
        migrations.CreateModel(
            name='SelectableAttribute_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SelectableAttribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.AtrributeChoises', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Все Selectable',
                'verbose_name_plural': 'Все Selectable',
                'db_table': 'attr_values_selectable',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=catalog.storage.OverwriteStorage(), unique=True, upload_to=catalog.models.ProductImages.get_file_path, verbose_name='Изображение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображения товаров',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'c_product_imgs',
            },
        ),
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('file', models.FileField(upload_to=catalog.models.ProductFiles.get_file_path, verbose_name='Файл')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Файлы товаров',
                'verbose_name_plural': 'Файлы товаров',
                'db_table': 'c_product_docs',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='selectable_attr_list',
            field=models.ManyToManyField(blank=True, to='catalog.SelectableAttribute', verbose_name='Выбираемые атрибуты для категории'),
        ),
        migrations.CreateModel(
            name='Attribute_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Все атрибуты',
                'verbose_name_plural': 'Все атрибуты',
                'db_table': 'attr_values',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attribute_measure', verbose_name='Ед. Измерения'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attribute_title', verbose_name='Атрибут'),
        ),
    ]
