# Generated by Django 2.2.15 on 2020-10-12 13:19

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201012_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=catalog.models.ProductFiles.get_file_path, verbose_name='Файл')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Файлы товаров',
                'verbose_name_plural': 'Файлы товаров',
            },
        ),
    ]
