# Generated by Django 2.2.15 on 2020-10-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productfiles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtrributeChoises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choise', models.CharField(max_length=120, unique=True, verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Вариант атрибутов',
                'verbose_name_plural': 'Варианты атрибутов',
            },
        ),
        migrations.CreateModel(
            name='SelectableAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Наименование')),
                ('measure', models.ManyToManyField(to='catalog.AtrributeChoises', verbose_name='Варианты')),
            ],
            options={
                'verbose_name': '(5) Выбираемый атрибут',
                'verbose_name_plural': '(5) Выбираемые атрибуты',
            },
        ),
        migrations.CreateModel(
            name='SelectableAttribute_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SelectableAttribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.AtrributeChoises', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Пул выбираемых атрибутов',
                'verbose_name_plural': 'Пул выбираемых атрибутов',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='selectable_attr_list',
            field=models.ManyToManyField(blank=True, to='catalog.SelectableAttribute', verbose_name='Выбираемые атрибуты для категории'),
        ),
    ]
