# Generated by Django 2.2.15 on 2020-10-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201013_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '(6) Заказ', 'verbose_name_plural': '(6) Заказы'},
        ),
        migrations.RenameField(
            model_name='selectableattribute',
            old_name='measure',
            new_name='choise',
        ),
    ]
