# Generated by Django 2.2.15 on 2020-10-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201013_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectableattribute',
            old_name='choise',
            new_name='choises',
        ),
    ]
